### ISSUE TITLE
UTF-8 BOM is output as "?", can result in incorrect `--ackmate` offsets

### ISSUE THREAD

**Issue by kcbanner** [JFLarvoire/the_silver_searcher#5]
I ran into a file with a UTF-8 BOM that results in printing a `?` character when the output is redirected to a file.

The simplest repro of the issue, is a file containing the bytes `ef bb bf 74`, then run `ag "t" file > out`. 

Then `out` contains:

```
1:?t
```

Confirmed that the `?` in that output is just the byte 0x3f (not some other display issue).

If you don't redirect the output to a file (ie `ag "t" file`):

```
$ ag "t" file
1:﻿t
```

This seems to be unique to this port (cygwin ag outputs the 3 byte BOM into the output file itself). 

This may very well be intended behavior (no way to properly encode the BOM in the terminal output maybe?), if so please disregard. I'm not even sure what the correct behavior in this case is.

Another side effect is that the  `--ackmate` mode reports an incorrect starting offset, `ag --ackmate "t" test > out.ackmate`

```
1;3 1:?t\0
```

**Comment by JFLarvoire** [comment]
Hello Casey,

This version of ag.exe uses the current console code page for its output on the standard output, unless the standard output goes to the console itself, in which case it uses UTF-16.
This is done for compatibility with Microsoft own console tools, which themselves work this way. And this maximizes the chances that non-ASCII characters be processed and displayed correctly in any command pipeline, on non-US versions of Windows in their default code page. Actually this is the main reason why I developed this port of ag.exe, because all other ports displayed garbage for French-specific characters, like the ç in my first name, both in the file names and in the data content. For Asian users, things were even worse as _every_ character was garbage.

So if you pipe this ag.exe's stdout to another command, or to a file, it's converted to the current console code page. And the default code page used by US versions of Windows is code page 437, which does not contain the BOM character. Hence the ? you get.
If you want the output file to be encoded in UTF-8, and preserve the BOM, you have to first change the console code page to code page 65001.

This also explains the offset error you get with the --ackmate option. Ag.exe uses UTF-8 internally, and does the encoding conversion at the very end, when doing its output on stdout. When using code page 65001, the offset matches what's in the output file.

I had never used that --ackmate option, and never noticed the issue.
As there's an easy workaround using code page 65001, I'm inclined to leave things the way they are.
I'll just add a note in the help screen for the next version to clarify all this.

Jean-François

**Comment by kcbanner** [comment]
Thanks! I thought it might be some encoding issue. I'll just change the code page on my end (I'm reading command results in a visual studio extension, hence the `--ackmate`), thanks for the thorough explanation!
